name: zerotier_manager
description: "ZeroTier Admin"
publish_to: 'none'

version: 0.0.7+7

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: 0.19.0

  ## system
  provider: 6.1.2
  shared_preferences: 2.3.3

  # Bloc
  bloc: 8.1.4
  equatable: 2.0.7
  flutter_bloc: 8.1.6

  ## network
  http: 1.2.2
  go_router: 14.4.1

  ## 
  flutter_svg: 2.0.14 # svg images
  rive: 0.13.20

  ## UI
  cupertino_icons: 1.0.8
  font_awesome_flutter: 10.8.0

dev_dependencies:
  flutter_lints: 5.0.0
  flutter_launcher_icons: 0.14.1

flutter_intl:
  enabled: true
  arb_dir: lib/common/l10n
  template_arbs: lib/common/l10n/app_en.arb

flutter:
  uses-material-design: true
  generate: true  # Uncommented and properly indented

  assets:
    - assets/svg/back_light.svg
    - assets/svg/back_dark.svg
    - assets/rive/zerotier.riv

flutter_launcher_icons:
  android: true
  ios: true
  image_path_android: "assets/icon/icon-710x599-android.png"
  image_path_ios: "assets/icon/icon.png"
  adaptive_icon_foreground: "assets/icon/icon-foreground-432x432.png"
  adaptive_icon_background: "assets/icon/icon-background-432x432.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  remove_alpha_ios: true
  background_color_ios: "#000000"
  background_color_android: "#000000"
  # web: false
  # windows: false
  # macos: false